# Generated by Django 2.2.6 on 2019-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_big_number', models.BigIntegerField()),
                ('bytes_number', models.BinaryField()),
                ('is_true', models.BooleanField()),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to=None)),
                ('file_path', models.FilePathField(path=None)),
                ('float_number', models.FloatField()),
                ('photo', models.ImageField(height_field=100, upload_to=None, width_field=100)),
                ('number', models.IntegerField()),
                ('ip_adress', models.GenericIPAddressField()),
                ('is_good', models.NullBooleanField()),
                ('positive_number', models.PositiveIntegerField()),
                ('small_positive_number', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField()),
                ('small_integer', models.SmallIntegerField()),
                ('text', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('uuid', models.UUIDField()),
            ],
        ),
    ]
